<?php /* Smarty version 2.6.18, created on 2015-05-06 12:41:49
         compiled from views/products/components/product_features_short_list.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'date_format', 'views/products/components/product_features_short_list.tpl', 8, false),array('modifier', 'default', 'views/products/components/product_features_short_list.tpl', 11, false),array('modifier', 'trim', 'views/products/components/product_features_short_list.tpl', 27, false),array('function', 'set_id', 'views/products/components/product_features_short_list.tpl', 27, false),)), $this); ?>
<?php  ob_start();  ?><?php ob_start(); ?>
<?php if ($this->_tpl_vars['features']): ?>
<?php echo ''; ?><?php if (! $this->_tpl_vars['no_container']): ?><?php echo '<p class="features-list description">'; ?><?php endif; ?><?php echo ''; ?><?php $_from = $this->_tpl_vars['features']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['features_list'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['features_list']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['feature']):
        $this->_foreach['features_list']['iteration']++;
?><?php echo ''; ?><?php if ($this->_tpl_vars['feature']['prefix']): ?><?php echo ''; ?><?php echo $this->_tpl_vars['feature']['prefix']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['feature']['feature_type'] == 'D'): ?><?php echo ''; ?><?php echo smarty_modifier_date_format($this->_tpl_vars['feature']['value_int'], ($this->_tpl_vars['settings']['Appearance']['date_format'])); ?><?php echo ''; ?><?php elseif ($this->_tpl_vars['feature']['feature_type'] == 'M'): ?><?php echo ''; ?><?php $_from = $this->_tpl_vars['feature']['variants']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['ffev'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['ffev']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['v']):
        $this->_foreach['ffev']['iteration']++;
?><?php echo ''; ?><?php echo smarty_modifier_default(@$this->_tpl_vars['v']['variant'], @$this->_tpl_vars['v']['value']); ?><?php echo ''; ?><?php if (! ($this->_foreach['ffev']['iteration'] == $this->_foreach['ffev']['total'])): ?><?php echo ', '; ?><?php endif; ?><?php echo ''; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php elseif ($this->_tpl_vars['feature']['feature_type'] == 'S' || $this->_tpl_vars['feature']['feature_type'] == 'N' || $this->_tpl_vars['feature']['feature_type'] == 'E'): ?><?php echo ''; ?><?php echo smarty_modifier_default(@$this->_tpl_vars['feature']['variant'], @$this->_tpl_vars['feature']['value']); ?><?php echo ''; ?><?php elseif ($this->_tpl_vars['feature']['feature_type'] == 'C'): ?><?php echo ''; ?><?php echo $this->_tpl_vars['feature']['description']; ?><?php echo ''; ?><?php elseif ($this->_tpl_vars['feature']['feature_type'] == 'O'): ?><?php echo ''; ?><?php echo $this->_tpl_vars['feature']['value_int']; ?><?php echo ''; ?><?php else: ?><?php echo ''; ?><?php echo $this->_tpl_vars['feature']['value']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['feature']['suffix']): ?><?php echo ''; ?><?php echo $this->_tpl_vars['feature']['suffix']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if (! ($this->_foreach['features_list']['iteration'] == $this->_foreach['features_list']['total'])): ?><?php echo ' / '; ?><?php endif; ?><?php echo ''; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php if (! $this->_tpl_vars['no_container']): ?><?php echo '</p>'; ?><?php endif; ?><?php echo ''; ?>

<?php endif; ?><?php $this->_smarty_vars['capture']['template_content'] = ob_get_contents(); ob_end_clean(); ?><?php if (trim($this->_smarty_vars['capture']['template_content'])): ?><?php if ($this->_tpl_vars['auth']['area'] == 'A'): ?><span class="cm-template-box" template="views/products/components/product_features_short_list.tpl" id="<?php echo smarty_function_set_id(array('name' => "views/products/components/product_features_short_list.tpl"), $this);?>
"><img class="cm-template-icon hidden" src="<?php echo $this->_tpl_vars['images_dir']; ?>
/icons/layout_edit.gif" width="16" height="16" alt="" /><?php echo $this->_smarty_vars['capture']['template_content']; ?>
<!--[/tpl_id]--></span><?php else: ?><?php echo $this->_smarty_vars['capture']['template_content']; ?>
<?php endif; ?><?php endif; ?><?php  ob_end_flush();  ?>